# Array creation routines

Create a new array of 2*2 integers, without initializing entries.

In [1]:
import numpy as np

In [11]:
  np.array(((0,0),(0,0)))
  np.array([[0,0],[0,0]])
  np.array([(0,0),(0,0)])

array([[0, 0],
       [0, 0]])

In [6]:
X = np.array([[1,2,3], [4,5,6]], np.int32)


Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [9]:
## Ones and zeros

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [19]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [21]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [33]:
x = np.arange(4, dtype=np.int64)
x

array([0, 1, 2, 3], dtype=int64)

In [35]:
x=np.ones(4,dtype=np.int)
x

array([1, 1, 1, 1])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [37]:
x = np.zeros(4,np.int64)
x

array([0, 0, 0, 0], dtype=int64)

Create a new array of 2*5 uints, filled with 6.

In [41]:
np.array(([6,6],[6,6],[6,6],[6,6],[6,6]))
np.array(((6,6,6,6,6),(6,6,6,6,6)))

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [42]:
Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

SyntaxError: invalid syntax (<ipython-input-42-fa4c5996dc5d>, line 1)

In [49]:
x = np.arange(4, dtype=np.int)
np.array([6,6,6,6])

array([6, 6, 6, 6])

## From existing data

Create an array of [1, 2, 3].

In [50]:
np.array([1,2,3])

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [52]:
x = [1,2]
x=np.array(x)
x

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [54]:
X = np.array([[1, 2], [3, 4]])
np.matrix(X)
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [59]:
x = [1, 2]
x=np.array(x,dtype=np.float)
x

array([1., 2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [61]:
x = np.array([30])
x=x[0]

30

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [66]:
x = np.array([1, 2, 3])
id(x)
import copy
y=copy.copy(x)
id(y)

85051472

## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [73]:
np.arange(2,102,2,dtype=np.int)
np.linspace(2,100,num=50,endpoint=True,dtype=np.int,retstep=True)

(array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
         54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
         80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100]), 2.0)

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [75]:
np.linspace(3,10,num=50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [88]:
np.linspace(np.log(3),np.log(10),num=50)

array([1.09861229, 1.12318316, 1.14775404, 1.17232491, 1.19689578,
       1.22146666, 1.24603753, 1.2706084 , 1.29517928, 1.31975015,
       1.34432102, 1.3688919 , 1.39346277, 1.41803364, 1.44260452,
       1.46717539, 1.49174627, 1.51631714, 1.54088801, 1.56545889,
       1.59002976, 1.61460063, 1.63917151, 1.66374238, 1.68831325,
       1.71288413, 1.737455  , 1.76202587, 1.78659675, 1.81116762,
       1.8357385 , 1.86030937, 1.88488024, 1.90945112, 1.93402199,
       1.95859286, 1.98316374, 2.00773461, 2.03230548, 2.05687636,
       2.08144723, 2.1060181 , 2.13058898, 2.15515985, 2.17973073,
       2.2043016 , 2.22887247, 2.25344335, 2.27801422, 2.30258509])

## Building matrices

In [77]:
Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

SyntaxError: invalid syntax (<ipython-input-77-a13a87493edf>, line 1)

In [82]:
X = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
X.diagonal()               

array([ 0,  5, 10])

In [78]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
X.diagonal()

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [83]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [85]:
np.array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [86]:
np.array([[0,0,0],[4,0,0],[7,8,0],[10,11,12]])

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [87]:
np.array([[1,2,3],[4,5,6],[0,8,9],[0,0,12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])