In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.0'

In [4]:
x = [1,2]
y = [[4, 1], [2, 2]]
np.dot(x, y)#矩阵点乘

array([8, 5])

In [5]:
np.dot(y, x)

array([6, 6])

In [6]:
np.matmul(x, y)#计算内积，与dot等效

array([8, 5])

In [7]:
np.inner(x, y)#内积

array([6, 6])

In [8]:
np.inner(y, x)

array([6, 6])

In [11]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))#矩阵乘法

[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


In [12]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))#向量乘法，不是向量的会展开成向量再计算
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())#计算所有元素的和

30
30
30
30
30


In [13]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print(np.outer(x, y))#向量外积，只用于一维
print(np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


In [17]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
np.linalg.cholesky(x)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [19]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q,r = np.linalg.qr(x)
print('q=',q)
print('r=',r)

q= [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]]
r= [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [21]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U,s,V = np.linalg.svd(x)
print('U=',U)
print('s=',s)
print('V=',V)

U= [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
s= [3.       2.236068 2.       0.      ]
V= [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]
 [-0.8944272  0.         0.         0.         0.4472136]]


In [25]:
x = np.diag((1, 2, 3))
eigenvals = np.linalg.eig(x)[0]
print("eigenvalues are", eigenvals)
eigenvecs = np.linalg.eig(x)[1]
print("eigenvectors are", eigenvecs)

eigenvalues are [1. 2. 3.]
eigenvectors are [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
print(np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


In [28]:
x = np.arange(1, 10).reshape((3, 3))
print(np.linalg.norm(x,'fro'))
print(np.linalg.cond(x,'fro'))

16.881943016134134
3.193239515623568e+17


In [29]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)

-2.0000000000000004

In [30]:
x = np.eye(4)
np.linalg.matrix_rank(x)

4

In [34]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.slogdet(x)

(-1.0, 0.6931471805599455)

In [35]:
x = np.eye(4)
np.trace(x)

4.0

In [36]:
x = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])