# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [2]:
x = np.array([[1,4],[3,1]])
np.sort(x, axis=1)

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [3]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((first_names, surnames)) #排序时优先照顾靠后的列

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])
np.argsort(x, axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [28]:
x = np.random.permutation(10)
print(x)
print(np.partition(x, 5))

[7 2 0 9 8 5 6 1 3 4]
[2 1 0 3 4 5 6 7 9 8]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [27]:
x = np.random.permutation(10)
print(x)
print(np.partition(x, 3))

[0 4 9 8 7 3 6 2 1 5]
[2 1 0 3 4 5 6 8 9 7]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [11]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)
print("maximum values = ", np.max(x, 1))
print("max indices =", np.argmax(x, 1))
print("minimum values =", np.min(x, 1))
print("min indices =", np.argmin(x, 1))

x = [[0 9 1 6 2]
 [3 5 4 8 7]]
maximum values =  [9 8]
max indices = [1 3]
minimum values = [0 3]
min indices = [0 0]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [12]:
x = np.array([[np.nan, 4], [3, 2]])
print("maximum values = ", np.nanmax(x, 1))
print("max indices =", np.nanargmax(x, 1))
print("minimum values =", np.nanmin(x, 1))
print("min indices =", np.nanargmin(x, 1))

maximum values =  [4. 3.]
max indices = [1 0]
minimum values = [4. 2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [15]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print("Values bigger than 2 =", x[x>2])
print("Their indices are", np.nonzero(x>2))#返回输入数组中非零元素的索引
print("Their indices are", np.where(x>2))

Values bigger than 2 = [3 3 5]
Their indices are (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))
Their indices are (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [16]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.flatnonzero(x)

array([0, 1, 2, 3, 4, 5], dtype=int64)

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [17]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x <0, 0, x)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [18]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [19]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5