# Logic functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

## Truth value testing


Q1. Let x be an arbitrary array. Return True if none of the elements of x is zero. Remind that 0 evaluates to False in python.


In [7]:
x = np.array([1,2,3])
#(x != 0).all()
np.all(x)

True

In [4]:
x = np.array([1,0,3])
#(x != 0).all()
np.all(x)

False

Q2. Let x be an arbitrary array. Return True if any of the elements of x is non-zero.

In [8]:
x = np.array([1,0,0])
#(x != 0).any()
np.any(x)

True

In [6]:
x = np.array([0,0,0])
#(x != 0).any()
np.any(x)

False

## Array contents


Q3. Predict the result of the following code.

In [10]:
x = np.array([1, 0, np.nan, np.inf])
print(np.isfinite(x))

[ True  True False False]


Q4. Predict the result of the following code.

In [11]:
x = np.array([1, 0, np.nan, np.inf])
print(np.isinf(x))

[False False False  True]


Q5. Predict the result of the following code.

In [12]:
x = np.array([1, 0, np.nan, np.inf])
print(np.isnan(x))

[False False  True False]


## Array type testing

Q6. Predict the result of the following code.

In [13]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.iscomplex(x))

[ True False False False False  True]


Q7. Predict the result of the following code.

In [14]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.isreal(x))

[False  True  True  True  True False]


Q8. Predict the result of the following code.

In [15]:
print(np.isscalar(3))

True


In [16]:
print(np.isscalar([3])) #list

False


In [17]:
print(np.isscalar(True)) # True==1(num)

True


## Logical operations

Q9. Predict the result of the following code.

In [18]:
print(np.logical_and([True, False], [False, False]))

[False False]


In [19]:
print(np.logical_or([True, False, True], [True, False, False]))

[ True False  True]


In [20]:
print(np.logical_xor([True, False, True], [True, False, False]))

[False False  True]


In [21]:
print(np.logical_not([True, False, 0, 1]))

[False  True  True False]


## Comparison

Q10. Predict the result of the following code.

In [22]:
print(np.allclose([3], [2.999999]))

True


In [23]:
print(np.array_equal([3], [2.999999]))

False


Q11. Write numpy comparison functions such that they return the results as you see.

In [25]:
x = np.array([4, 5])
y = np.array([2, 5])
np.greater(x, y)

array([ True, False])

In [26]:
np.greater_equal(x, y)

array([ True,  True])

In [27]:
np.less(x, y)

array([False, False])

In [28]:
np.less_equal(x, y)

array([False,  True])

Q12. Predict the result of the following code.

In [29]:
print(np.equal([1, 2], [1, 2.000001]))

[ True False]


In [30]:
print(np.isclose([1, 2], [1, 2.000001]))

[ True  True]
