# Soring, searching, and counting

In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.5'

In [4]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [53]:
x = np.array([[1,4],[3,1]])
out=np.sort(x,axis=-1)
np.array_equal(out,x)

False

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [52]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((first_names, surnames))

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [17]:
x = np.array([[1,4],[3,1]])
np.argsort(x, axis=1)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [76]:
x = np.random.permutation(10)
print("x =", x)
out = np.partition(x, 5)
#先对数组排序（升序），然后以索引是i的元素为基准，将元素分成两部分，即大于该元素的放在后面，小于该元素的放后面
np.array_equal(x, out)
np.partition(x,(2,4))


x = [2 5 0 4 3 1 8 6 7 9]


array([0, 1, 2, 3, 4, 5, 8, 6, 7, 9])

In [67]:
Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

SyntaxError: invalid syntax (<ipython-input-67-c6d8f7a80826>, line 1)

In [84]:
x = np.random.permutation(10)
print ("x =", x)
partitioned=np.partition(x,3)
indices=np.argpartition(x,3)
print("partitioned=",partitioned)
print("indices=",indices)
np.array_equal(x[indices],partitioned)

x = [6 7 8 9 3 0 2 1 5 4]
partitioned= [1 0 2 3 4 7 9 8 5 6]
indices= [7 5 6 4 9 1 3 2 8 0]


array([1, 0, 2, 3, 4, 7, 9, 8, 5, 6])

## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [86]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x) 
x_max=np.max(x,axis=1)
print(x_max)

x_min=np.min(x,axis=1)
print(x_min)
print(np.argmax(x,1))

print(np.argmin(x,1))

x = [[7 4 0 8 1]
 [5 3 9 6 2]]
[8 9]
[0 2]
[3 2]
[2 4]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [87]:
x = np.array([[np.nan, 4], [3, 2]])
print(np.nanmax(x,axis=1))
print(np.nanmin(x,axis=1))
print(np.nanargmax(x,1))
print(np.nanargmin(x,1))

[4. 3.]
[4. 2.]
[1 0]
[1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [95]:
x = np.array([[1, 2, 3], [1, 3, 5]])
x[x>2]
np.where(x>2)
#找到非零数的索引
x>2
print("Values bigger than 2 =",x[x>2])
x[np.nonzero(x > 2)] 
np.extract(x > 2, x)
np.nonzero(x > 2)#找到x>2的数的索引
(x>2).nonzero()

Values bigger than 2 = [3 3 5]


(array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))

Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [96]:
x = np.array([[1, 2, 3], [1, 3, 5]])
y=x.flatten()>2
x.flatten()[y]
#np.flatnonzero(x>2)
np.cc(np.flatnonzero(x), x.ravel().nonzero())

True

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [12]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x<0,0,x)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [97]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [11]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5