# Linear algebra

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.5'

## Matrix and vector products

Q1. Predict the results of the following code.

In [5]:
x = [1,2]
y = [[4, 1], [2, 2]]
print(np.dot(x, y))
print(np.dot(y, x))
print(np.matmul(x, y))#
print(np.inner(x,y))
print(np.inner(y,x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [6]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))

[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [8]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


Q4. Predict the results of the following code.

In [9]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
np.inner(x, y)
np.inner(y, x)
np.outer(x, y)
np.outer(y, x)

array([['a', 'b'],
       ['aa', 'bb']], dtype=object)

## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [10]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
#获得下三角
np.linalg.cholesky(x)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

Q6. Compute the qr factorization of x and verify it.

In [13]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
#因素分解
q,r=np.linalg.qr(x)
print(q)
print(r)

[[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]]
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [18]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
#奇异值分解
u,s,v=np.linalg.svd(x,full_matrices=False)
print(u)
print(s)
print(v)
np.allclose(np.dot(u, np.dot(np.diag(s), v)), x)

[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
[3.       2.236068 2.       0.      ]
[[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


True

## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [23]:
x = np.diag((1, 2, 3))#特征值和特征向量计算
eigenvals = np.linalg.eig(x)[0]
eigenvals_ = np.linalg.eigvals(x)
eigenvecs=np.linalg.eig(x)[1]
print("eigenvals are=",eigenvals)
print("eigenvecs are=",eigenvecs)

eigenvals are= [1. 2. 3.]
eigenvecs are= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [24]:
print (np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [27]:
x = np.arange(1, 10).reshape((3, 3))
print(np.linalg.norm(x, 'fro'))
print(np.linalg.cond(x, 'fro'))

16.881943016134134
3.193239515623568e+17


Q11. Calculate the determinant of x.

In [28]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)#计算行列式

-2.0000000000000004

Q12. Calculate the rank of x.

In [31]:
x = np.eye(4)
np.linalg.matrix_rank(x)
np.linalg.svd(x)[1].size

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [34]:
x = np.arange(1, 5).reshape((2, 2))
sign,logdet=np.linalg.slogdet(x)
det=np.linalg.det(x)
sign == np.sign(det)
logdet == np.log(np.abs(det))

True

Q14. Return the sum along the diagonal of x.

In [37]:
x = np.eye(4)
np.trace(x)
x.diagonal().sum()

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [40]:
x = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(x)
np.allclose(np.dot(x,np.linalg.inv(x)),np.eye(2))

True