# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.1'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [4]:
x = np.array([[1,4],[3,1]])
print(np.sort(x,axis=1))

[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [9]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
print(np.lexsort((surnames,first_names)))

[1 2 0]


Q3. Get the indices that would sort x along the second axis.

In [11]:
x = np.array([[1,4],[3,1]])
print(np.argsort(x))

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [48]:
x = np.random.permutation(10)
print("x =", x)
print('\nCheck the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5')
print(np.partition(x,5))


x = [1 3 7 4 9 8 2 6 5 0]

Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5
[0 1 4 3 2 5 7 6 8 9]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [47]:
x = np.random.permutation(10)
print("x =", x)
print('partitioned = ',np.partition(x,3))
print('indices = ',np.argpartition(x,3))


x = [0 6 7 5 3 2 1 4 9 8]
partitioned =  [2 0 1 3 6 5 7 4 9 8]
indices =  [5 0 6 4 1 3 2 7 8 9]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [43]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)
print('maximum values = ',np.max(x,1))
print('max indices = ',np.argmax(x,1))
print('minimum values = ',np.min(x,1))
print('min indices = ',np.argmin(x,1))


x = [[4 2 7 0 3]
 [8 5 6 9 1]]
maximum values =  [7 9]
max indices =  [2 3]
minimum values =  [0 1]
min indices =  [3 4]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [38]:
x = np.array([[np.nan, 4], [3, 2]])
print('maximum values ignoring NaNs = ',np.nanmax(x,1))
print('max indices = ',np.where(np.nanmax(x,1)))
print('minimum values ignoring NaNs = ',np.nanmin(x,1))
print('min indices = ',np.where(np.nanmin(x,1)))

maximum values ignoring NaNs =  [4. 3.]
max indices =  (array([0, 1], dtype=int64),)
minimum values ignoring NaNs =  [4. 2.]
min indices =  (array([0, 1], dtype=int64),)


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [24]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print('Values bigger than 2 = ',x[x>2])
print('Their indices are ',np.where(x>2))

Values bigger than 2 =  [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [22]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print(np.flatnonzero(x>2))

[2 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [18]:
x = np.arange(-5, 4).reshape(3, 3)
x[x<0]=0
print(x)
#print(np.where(x<0,0,x))

[[0 0 0]
 [0 0 0]
 [1 2 3]]
[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [14]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
print(np.searchsorted(x,y))

[0 2 1 3]


## Counting

Q12. Get the number of nonzero elements in x.

In [12]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5