# Array creation routines

## Ones and zeros

In [1]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [7]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [32]:
X = np.array([[1,2,3], [4,5,6]], np.int32)


array([[1, 2, 3],
       [4, 5, 6]])

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [12]:
np.ones((3,2),dtype=float)

array([[1, 1],
       [1, 1],
       [1, 1]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [14]:
x = np.arange(4, dtype=np.int64)
x

array([0, 1, 2, 3], dtype=int64)

In [15]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [58]:
x = np.arange(4, dtype=np.int64)


array([0, 0, 0, 0], dtype=int64)

Create a new array of 2*5 uints, filled with 6.

In [17]:
np.full((2,5),6,dtype=int)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [26]:
x = np.arange(4, dtype=np.int64)
y=np.arange(6,dtype=np.int64)
y

array([0, 1, 2, 3, 4, 5], dtype=int64)

## From existing data

Create an array of [1, 2, 3].

In [29]:
a=np.array([1,2,3])
a

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [33]:
x = np.array([1,2])
x

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [36]:
X = np.matrix([[1, 2], [3, 4]])
X


matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [128]:
x = np.array([1, 2],dtype=float)
x


array([1., 2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [75]:
x = np.array(30)
x=30
print(x)


30


Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [79]:
x1 = np.array([1, 2, 3])
x2 = np.array([1, 2, 3])
id1=id(x1)
id2=id(x2)
print(id1,x1)
print(id2,x2)

86858208 [1 2 3]
86857888 [1 2 3]


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [83]:
np.linspace(2,100,50,dtype=int)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [85]:
np.linspace(3,10,50,dtype=float)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [97]:
np.logspace(3,10,50,dtype=float,base=9.7)

array([9.12673000e+02, 1.26264887e+03, 1.74682735e+03, 2.41667013e+03,
       3.34337249e+03, 4.62543046e+03, 6.39910957e+03, 8.85292810e+03,
       1.22476940e+04, 1.69442253e+04, 2.34417003e+04, 3.24307132e+04,
       4.48666754e+04, 6.20713628e+04, 8.58734026e+04, 1.18802632e+05,
       1.64358986e+05, 2.27384493e+05, 3.14577918e+05, 4.35206752e+05,
       6.02092219e+05, 8.32972005e+05, 1.15238553e+06, 1.59428216e+06,
       2.20562958e+06, 3.05140580e+06, 4.22150549e+06, 5.84029453e+06,
       8.07982845e+06, 1.11781396e+07, 1.54645370e+07, 2.13946069e+07,
       2.95986363e+07, 4.09486033e+07, 5.66508569e+07, 7.83743359e+07,
       1.08427954e+08, 1.50006009e+08, 2.07527687e+08, 2.87106772e+08,
       3.97201452e+08, 5.49513312e+08, 7.60231059e+08, 1.05175116e+09,
       1.45505828e+09, 2.01301857e+09, 2.78493569e+09, 3.85285408e+09,
       5.33027913e+09, 7.37424127e+09])

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [99]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
print(np.diagonal(X))


[ 0  5 10]


Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [108]:
b=[1,2,3,4]
np.diag(b)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [126]:
c=np.ones((3,5))
c1=np.tril(c,k=-1)
c1

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [120]:
d=np.arange(1,13).reshape(4,3)
d1=np.tril(d,k=-1)
d1

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [123]:
e=np.arange(1,13).reshape(4,3)
e1=np.triu(e,k=-1)
e1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])