# Array manipulation routines

In [3]:
import numpy as np

In [3]:
np.__version__ # 查看numpy的版本号

'1.15.1'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [9]:
a=np.full((2,150),1,dtype=float)
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [7]:
b=np.arange(1,7)
b[1],b[2],b[3],b[4]=b[3],b[1],b[4],b[2]
print(b)

[1 4 2 5 3 6]


Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [13]:
c=np.arange(1,7)
print(c[4])

5


Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [39]:
d=np.ones((3,4,5))
d.shape=(4,3,5)
d.shape

(4, 3, 5)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [46]:
e=np.arange(0,12).reshape((3,4))
e.resize((4,3))
e.shape

(4, 3)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [61]:
f=np.arange(0,12).reshape((3,4))
f.resize((3,1,4))
f.shape

(3, 1, 4)

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [74]:
g=np.arange(0,12).reshape((3,4,1))
g.shape=(3,4)
g.shape


(3, 4)

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [82]:
x=np.arange(1,7).reshape((2,3))
y=np.arange(7,13).reshape((2,3))
z=np.concatenate([x,y],axis=1)
print(z)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [87]:
x=np.arange(1,7).reshape((2,3))
y=np.arange(7,13).reshape((2,3))
z=np.concatenate([x,y],axis=0)
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [124]:
x=[[1,2,3]]
y=[[4,5,6]]
z=np.concatenate([x,y],axis=0)
print(z.T)


[[1 4]
 [2 5]
 [3 6]]


Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [123]:
x=[[1,2,3]]
y=[[4,5,6]]
z=np.concatenate([x,y],axis=0)
w=z.T
w.shape=(3,1,2)
print(w)

[[[1 4]]

 [[2 5]]

 [[3 6]]]


Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [127]:
x=np.arange(1,10)
np.hsplit(x,(4,6))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [143]:
x=np.arange(0,16).reshape(4,4)
y=np.hsplit(x,(3,))
print(y)

[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [147]:
x=np.arange(0,16).reshape(4,4)
y=np.hsplit(x,2)
print(y)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [152]:
x=np.arange(0,16).reshape(4,4)
y=np.vsplit(x,2)
print(y)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [159]:
x=np.array([0,1,2])
y=np.tile(x,4).reshape(2,6)
print(y)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [160]:
x=np.array([0,1,2])
y=np.repeat(x,2)
print(y)

[0 0 1 1 2 2]


Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [193]:
x=np.array([0,0,0,1,2,3,0,2,1,0])
y=np.delete(x,(0,1,2,9))
print(y)

[1 2 3 0 2 1]


Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [222]:
x=[2,2, 1, 5, 4, 5, 1, 2, 3]
y=set(x)
for item in y:
    print(x.count(item))
#x.count(y)

2
3
1
1
2


Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [248]:
x=np.arange(1,5).reshape(2,2)
y=np.flip(x,axis=1)
print(y)

[[2 1]
 [4 3]]


Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [247]:
x=np.arange(1,5).reshape(2,2)
y=np.flip(x,axis=0)
print(y)

[[3 4]
 [1 2]]


Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [122]:
x=np.arange(1,5).reshape(2,2)
y=np.rot90(x)

[[2 4]
 [1 3]]


Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [277]:
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.roll(x,1,axis=1)
print(y)


[[4 1 2 3]
 [8 5 6 7]]
