# Mathematical functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.0'

## Trigonometric functions

Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [3]:
x = np.array([0., 1., 30, 90])
print('sine:', np.sin(x))
print('cosine:', np.cos(x))
print('tangent:', np.tan(x))

sine: [ 0.          0.84147098 -0.98803162  0.89399666]
cosine: [ 1.          0.54030231  0.15425145 -0.44807362]
tangent: [ 0.          1.55740772 -6.4053312  -1.99520041]


Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [4]:
x = np.array([-1., 0, 1.])
print('inverse sine:', np.arcsin(x))
print('inverse cosine:', np.arccos(x))
print('inverse tangent:', np.arctan(x))

inverse sine: [-1.57079633  0.          1.57079633]
inverse cosine: [3.14159265 1.57079633 0.        ]
inverse tangent: [-0.78539816  0.          0.78539816]


Q3. Convert angles from radians to degrees.

In [6]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
np.degrees(x)

array([-180.,  -90.,   90.,  180.])

Q4. Convert angles from degrees to radians.

In [7]:
x = np.array([-180.,  -90.,   90.,  180.])
np.radians(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

## Hyperbolic functions

Q5. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.

In [8]:
x = np.array([-1., 0, 1.])
print(np.sinh(x))
print(np.cosh(x))
print(np.tanh(x))

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


## Rounding

Q6. Predict the results of these, paying attention to the difference among the family functions.

In [9]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x)#四舍五入取整
out2 = np.floor(x)#取小于等于给定元素的最大整数
out3 = np.ceil(x)#取大于等于给定元素的最小整数
out4 = np.trunc(x)#取整数部分
out5 = [round(elem) for elem in x]#四舍五入取整
round()
print(out1)
print(out2)
print(out3)
print(out4)
print(out5)

[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]
[2.0, 2.0, 2.0, 3.0, -2.0, -2.0, -3.0]


Q7. Implement out5 in the above question using numpy.

In [10]:
np.floor(np.abs(x) + 0.5) * np.sign(x)

array([ 2.,  2.,  3.,  3., -2., -3., -3.])

## Sums, products, differences

Q8. Predict the results of these.

In [11]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = [np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "",
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "",
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),#累积和
        "",
        np.cumprod(x),
        np.cumprod(x, axis=0),#累积积
        np.cumprod(x, axis=1),
        "",
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]
           
for out in outs:
    if out == "":
        pass
        print
    else:
        pass
        print("->", out)


-> 36
-> [ 6  8 10 12]
-> [[10]
 [26]]
-> 40320
-> [ 5 12 21 32]
-> [[  24]
 [1680]]
-> [ 1  3  6 10 15 21 28 36]
-> [[ 1  2  3  4]
 [ 6  8 10 12]]
-> [[ 1  3  6 10]
 [ 5 11 18 26]]
-> [    1     2     6    24   120   720  5040 40320]
-> [[ 1  2  3  4]
 [ 5 12 21 32]]
-> [[   1    2    6   24]
 [   5   30  210 1680]]
-> 1
-> [1 2 3 4]
-> [[1]
 [5]]
-> 8
-> [5 6 7 8]
-> [[4]
 [8]]
-> 4.5
-> [3. 4. 5. 6.]
-> [[2.5]
 [6.5]]
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:34: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison


Q9. Calculate the difference between neighboring elements, element-wise.

In [13]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)#一阶差分

array([ 1,  2,  3, -7])

Q10. Calculate the difference between neighboring elements, element-wise, and
prepend [0, 0] and append[100] to it.

In [14]:
x = np.array([1, 2, 4, 7, 0])
np.insert(np.append(np.diff(x), 100), 0, [0, 0])
#append在末尾添加，insert可选择插入的位置

array([  0,   0,   1,   2,   3,  -7, 100])

Q11. Return the cross product of x and y.

In [15]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x,y)

array([-3,  6, -3])

## Exponents and logarithms

Q12. Compute $e^x$, element-wise.

In [16]:
x = np.array([1., 2., 3.], np.float32)
np.exp(x)

array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

Q13. Calculate exp(x) - 1 for all elements in x.

In [17]:
x = np.array([1., 2., 3.], np.float32)
np.exp(x)-1

array([ 1.7182817,  6.389056 , 19.085537 ], dtype=float32)

Q14. Calculate $2^p$ for all p in x.

In [18]:
x = np.array([1., 2., 3.], np.float32)
np.exp2(x)

array([2., 4., 8.], dtype=float32)

Q15. Compute natural, base 10, and base 2 logarithms of x element-wise.

In [19]:
x = np.array([1, np.e, np.e**2])
print('natural log =', np.log(x))
print('common log =', np.log10(x))
print('base 2 log =', np.log2(x))

natural log = [0. 1. 2.]
common log = [0.         0.43429448 0.86858896]
base 2 log = [0.         1.44269504 2.88539008]


Q16. Compute the natural logarithm of one plus each element in x in floating-point accuracy.

In [22]:
x = np.array([1e-99, 1e-100])
np.log1p(x)#log(x+1)

0.999896315728952

## Floating point routines

Q17. Return element-wise True where signbit is set.

In [24]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])
np.signbit(x)


array([ True,  True,  True, False, False, False, False])

Q18. Change the sign of x to that of y, element-wise.

In [25]:
x = np.array([-1, 0, 1])
y = -1.1
np.copysign(x, y)

array([-1., -0., -1.])

## Arithmetic operations

Q19. Add x and y element-wise.

In [26]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
np.add(x,y)

array([0, 0, 0])

Q20. Subtract y from x element-wise.

In [27]:
x = np.array([3, 4, 5])
y = np.array(3)
np.subtract(x,y)

array([0, 1, 2])

Q21. Multiply x by y element-wise.

In [28]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
np.multiply(x,y)

array([ 3,  0, -5])

Q22. Divide x by y element-wise in two different ways.

In [31]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
print(np.divide(x,y))
print(np.floor_divide(x,y))#整除

[3.         2.         1.66666667]
[3. 2. 1.]


Q23. Compute numerical negative value of x, element-wise.

In [32]:
x = np.array([1, -1])
np.negative(x)#相反数

array([-1,  1])

Q24. Compute the reciprocal of x, element-wise.

In [33]:
x = np.array([1., 2., .2])
np.reciprocal(x)#倒数

array([1. , 0.5, 5. ])

Q25. Compute $x^y$, element-wise.

In [34]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
np.power(x,y)

array([[ 1,  4],
       [ 3, 16]], dtype=int32)

Q26. Compute the remainder of x / y element-wise in two different ways.

In [35]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
print(np.mod(x,y))#取余数,符号由除数决定
print(np.fmod(x,y))#符号由被除数决定

[1 0 1 1 0 1]
[-1  0 -1  1  0  1]


## Miscellaneous

Q27. If an element of x is smaller than 3, replace it with 3.
And if an element of x is bigger than 7, replace it with 7.

In [36]:
x = np.arange(10)
np.clip(x, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

Q28. Compute the square of x, element-wise.

In [37]:
x = np.array([1, 2, -1])
np.square(x)

array([1, 4, 1], dtype=int32)

Q29. Compute square root of x element-wise.


In [38]:
x = np.array([1., 4., 9.])
np.sqrt(x)

array([1., 2., 3.])

Q30. Compute the absolute value of x.

In [39]:
x = np.array([[1, -1], [3, -3]])
np.abs(x)

array([[1, 1],
       [3, 3]])

Q31. Compute an element-wise indication of the sign of x, element-wise.

In [40]:
x = np.array([1, 3, 0, -1, -3])
np.sign(x)

array([ 1,  1,  0, -1, -1])