# Soring, searching, and counting

In [2]:
import numpy as np

In [2]:
np.__version__

'1.15.1'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [4]:
x = np.array([[1,4],[3,1]])
np.sort(x, axis=1)  #按列排序

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [5]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((first_names, surnames)) #按姓、名排序返回索引

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [6]:
x = np.array([[1,4],[3,1]])
np.argsort(x, axis=1) #按列从小到大排序，返回对应索引

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [5]:
x = np.random.permutation(10)
print ("x =", x)
np.partition(x, 5)  #升序排

x = [7 1 5 0 6 8 3 2 4 9]


array([1, 0, 2, 4, 3, 5, 6, 7, 8, 9])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [6]:
x = np.random.permutation(10)
print ("x =", x)
print('partitioned =',np.partition(x,3))
print ('indices =',np.argpartition(x,3)) #索引

x = [9 0 3 7 2 1 6 4 5 8]
partitioned = [0 1 2 3 4 5 6 7 8 9]
indices = [1 5 4 2 7 8 6 3 9 0]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [11]:
x = np.random.permutation(10).reshape(2, 5)
print ("x =", x)
#x在第二轴上的最大值和最小值及其下标
print ("maximum values =", np.max(x, 1))
print ("max indices =", np.argmax(x, 1))
print ("minimum values =", np.min(x, 1))
print ("min indices =", np.argmin(x, 1))

x = [[3 4 8 2 5]
 [7 0 6 9 1]]
maximum values = [8 9]
max indices = [2 3]
minimum values = [2 0]
min indices = [3 1]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [12]:
x = np.array([[np.nan, 4], [3, 2]])
print ("maximum values ignoring NaNs =", np.nanmax(x, 1))
print ("max indices =", np.nanargmax(x, 1))
print ("minimum values ignoring NaNs =", np.nanmin(x, 1))
print ("min indices =", np.nanargmin(x, 1))

maximum values ignoring NaNs = [4. 3.]
max indices = [1 0]
minimum values ignoring NaNs = [4. 2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [13]:
x = np.array([[1, 2, 3], [1, 3, 5]])
#x中大于2的元素的值和下标。
print ("Values bigger than 2 =", x[x>2])
print ("Their indices are ", np.nonzero(x > 2))

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [14]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.flatnonzero(x>2)

array([2, 4, 5], dtype=int64)

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [15]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x <0, 0, x)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [17]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)#y按顺序插入x中的索引

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [18]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5