In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.0'

In [6]:
x = np.array([1,2,3])
np.all(x)#除了0其他数字转化成布尔型均为True

True

In [7]:
x = np.array([1,0,3])
np.all(x)#all表示每个元素都为True时返回True

False

In [8]:
x = np.array([1,0,0])
np.any(x)#any表示只要有元素为True就返回True

True

In [9]:
x = np.array([0,0,0])
np.any(x)

False

In [10]:
x = np.array([1, 0, np.nan, np.inf])
np.isfinite(x)#对数组逐元素进行判断，返回相同形状长度的布尔型数组

array([ True,  True, False, False])

In [11]:
x = np.array([1, 0, np.nan, np.inf])
np.isinf(x)#nan既不是有限值也不是无穷

array([False, False, False,  True])

In [12]:
x = np.array([1, 0, np.nan, np.inf])
np.isnan(x)

array([False, False,  True, False])

In [13]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.iscomplex(x)

array([ True, False, False, False, False,  True])

In [14]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.isreal(x)

array([False,  True,  True,  True,  True, False])

In [16]:
print(np.isscalar(3))#判断是否是标量
print(np.isscalar([3]))
print(np.isscalar(True))

True
False
True


In [17]:
print(np.logical_and([True, False], [False, False]))
print(np.logical_or([True, False, True], [True, False, False]))
print(np.logical_xor([True, False, True], [True, False, False]))#先取反再取或
print(np.logical_not([True, False, 0, 1]))#取反

[False False]
[ True False  True]
[False False  True]
[False  True  True False]


In [18]:
print(np.allclose([3], [2.999999]))#判断数组形状以及对应各元素是否相等，允许误差不超过0.00001
print(np.array_equal([3], [2.999999]))#判断数组形状以及对应各元素是否完全相等

True
False


In [20]:
x = np.array([4, 5])
y = np.array([2, 5])
print(np.greater(x, y))#大于
print(np.greater_equal(x, y))#大于等于
print(np.less(x, y))#小于
print(np.less_equal(x, y))#小于等于

[ True False]
[ True  True]
[False False]
[False  True]


In [24]:
print(np.equal([1, 2], [1, 2.000001]))
print(np.isclose([1, 2], [1, 2.000001]))

[ True False]
[ True  True]
