In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.0'

In [3]:
np.ones((10,10,3)).reshape(2,150)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

In [7]:
list(np.array([1,2,3,4,5,6]))

[1, 2, 3, 4, 5, 6]

In [11]:
np.linspace(1,6,6,dtype=int)[4]

5

In [13]:
x = np.ones((3,4,5))
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [16]:
x = x.reshape(4,3,5)
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [17]:
x.shape

(4, 3, 5)

In [19]:
x = np.zeros((3,4))
x = x.reshape(4,3)
x.shape

(4, 3)

In [22]:
x = np.ones((3,4))
x = x[:,np.newaxis,:]
x

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])

In [23]:
x.shape

(3, 1, 4)

In [26]:
x = np.ones((3,4,1))
x = x.squeeze(2)
x.shape

(3, 4)

In [31]:
x = np.arange(1,7,1).reshape(2,3)
y = np.arange(7,13,1).reshape(2,3)
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [32]:
np.concatenate((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
x = np.arange(1,4,1)
y = np.arange(4,7,1)
np.stack((x,y),1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
np.stack((x,y),1)[:,np.newaxis,:]

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

In [45]:
x = np.arange(1,10,1)
np.split(x,[4,6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

In [51]:
x = np.arange(16).reshape(2,2,4)
np.split(x,[3],axis=2)

[array([[[ 0,  1,  2],
         [ 4,  5,  6]],
 
        [[ 8,  9, 10],
         [12, 13, 14]]]), array([[[ 3],
         [ 7]],
 
        [[11],
         [15]]])]

In [53]:
x = np.arange(16).reshape(4,4)
np.split(x,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [54]:
x = np.arange(16).reshape(4,4)
np.split(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [55]:
x = np.arange(3)
np.resize(x,(2,6))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [56]:
x = np.arange(3)
np.repeat(x,2)

array([0, 0, 1, 1, 2, 2])

In [57]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])
np.delete(x,[0, 1, 2, 9])

array([1, 2, 3, 0, 2, 1])

In [58]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
np.unique(x,return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 3, 1, 1, 2], dtype=int64))

In [59]:
x = np.array([[1, 2], [3, 4]])
np.flip(x, axis=1)

array([[2, 1],
       [4, 3]])

In [61]:
x = np.array([[1, 2], [3, 4]])
np.flip(x,axis=0)

array([[3, 4],
       [1, 2]])

In [62]:
x = np.array([[1, 2], [3, 4]])
np.rot90(x)

array([[2, 4],
       [1, 3]])

In [65]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.roll(x, 1, axis=1)

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])