In [1]:
from __future__ import print_function
import numpy as np

In [2]:
np.__version__

'1.14.0'

In [5]:
x1 = np.array(['Hello', 'Say'], dtype=np.str)
x2 = np.array([' world', ' something'], dtype=np.str)
np.char.add(x1, x2)

array(['Hello world', 'Say something'], dtype='<U15')

In [6]:
x = np.array(['Hello ', 'Say '], dtype=np.str)
np.char.multiply(x, 3)

array(['Hello Hello Hello ', 'Say Say Say '], dtype='<U18')

In [8]:
x = np.array(['heLLo woRLd', 'Say sOmething'], dtype=np.str)
capitalized = np.char.capitalize(x)
lowered = np.char.lower(x)
uppered = np.char.upper(x)
swapcased = np.char.swapcase(x)
titlecased = np.char.title(x)
print("capitalized =", capitalized)
print("lowered =", lowered)
print("uppered =", uppered)
print("swapcased =", swapcased)
print("titlecased =", titlecased)

capitalized = ['Hello world' 'Say something']
lowered = ['hello world' 'say something']
uppered = ['HELLO WORLD' 'SAY SOMETHING']
swapcased = ['HEllO WOrlD' 'sAY SoMETHING']
titlecased = ['Hello World' 'Say Something']


In [14]:
x = np.array(['hello world', 'say something'], dtype=np.str)
centered = np.char.center(x, 20, fillchar="_")
left = np.char.ljust(x, 20, fillchar="_")
right = np.char.rjust(x, 20, fillchar="_")

print("centered =", centered)
print("left =", left)
print("right =", right)

centered = ['____hello world_____' '___say something____']
left = ['hello world_________' 'say something_______']
right = ['_________hello world' '_______say something']


In [15]:
x = np.array(['hello world', 'say something'], dtype=np.str)
encoded = np.char.encode(x, 'cp500')
decoded = np.char.decode(encoded, 'cp500')
print("encoded =", encoded)
print("decoded =", decoded)

encoded = [b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'
 b'\xa2\x81\xa8@\xa2\x96\x94\x85\xa3\x88\x89\x95\x87']
decoded = ['hello world' 'say something']


In [17]:
x = np.array(['hello world', 'say something'], dtype=np.str)
np.char.join(" ", x)

array(['h e l l o   w o r l d', 's a y   s o m e t h i n g'], dtype='<U25')

In [20]:
x = np.array(['   hello world   ', '\tsay something\n'], dtype=np.str)
stripped = np.char.strip(x)
lstripped = np.char.lstrip(x)
rstripped = np.char.rstrip(x)
print("stripped =", stripped)
print("lstripped =", lstripped)
print("rstripped =", rstripped)

stripped = ['hello world' 'say something']
lstripped = ['hello world   ' 'say something\n']
rstripped = ['   hello world' '\tsay something']


In [21]:
x = np.array(['Hello my name is John'], dtype=np.str)
np.char.split(x, sep=' ')

array([list(['Hello', 'my', 'name', 'is', 'John'])], dtype=object)

In [23]:
x = np.array(['Hello\nmy name is John'], dtype=np.str)
np.char.splitlines(x)

array([list(['Hello', 'my name is John'])], dtype=object)

In [25]:
x = np.array(['34'], dtype=np.str)
np.char.rjust(x, 4, fillchar='0')

array(['0034'], dtype='<U4')

In [26]:
x = np.array(['Hello nmy name is John'], dtype=np.str)
np.char.replace(x, 'John', 'Jim')

array(['Hello nmy name is Jim'], dtype='<U21')

In [27]:
x1 = np.array(['Hello', 'my', 'name', 'is', 'John'], dtype=np.str)
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'], dtype=np.str)
x1 != x2

array([False, False, False, False,  True])

In [28]:
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'], dtype=np.str)
np.char.count(x, 'l')

array([2, 0, 0, 0, 1])

In [32]:
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'], dtype=np.str)
np.char.find(x, 'l')

array([ 2, -1, -1, -1,  2])

In [33]:
x = np.array(['Hello', 'I', 'am', '20', 'years', 'old'], dtype=np.str)
out1 = np.char.isdigit(x)
out2 = np.char.islower(x)
out3 = np.char.isupper(x)
print("Digits only =", out1)
print("Lower cases only =", out2)
print("Upper cases only =", out3)

Digits only = [False False False  True False False]
Lower cases only = [False False  True False  True  True]
Upper cases only = [False  True False False False False]


In [34]:
x = np.array(['he', 'his', 'him', 'his'], dtype=np.str)
np.char.startswith(x, 'hi')

array([False,  True,  True,  True])