# Random Sampling

In [2]:
import numpy as np

In [2]:
np.__version__

'1.15.1'

In [3]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [6]:
np.random.rand(3, 2) #0-1随机数

array([[0.46023944, 0.30974333],
       [0.66380446, 0.14003861],
       [0.61422729, 0.5185623 ]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [10]:
x=np.random.standard_normal((1000, 1000))#N(0,1)随机数
print(np.mean(x),np.std(x))


0.0010555256645719915 0.9994851460006476


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [11]:
#0-3的离散随机数
np.random.randint(0, 4, (3, 2))

array([[1, 3],
       [0, 0],
       [1, 0]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [4]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']
for i in range(10):
    print (np.random.choice(x, p=[.3, .5, .2]))

b'3 out of 10'
b'2 out of 10'
b'2 out of 10'
b'2 out of 10'
b'3 out of 10'
b'2 out of 10'
b'5 out of 10'
b'2 out of 10'
b'3 out of 10'
b'3 out of 10'


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [16]:
np.random.choice(10, 3, replace=False)

array([2, 1, 5])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [19]:
x = np.arange(10)
np.random.shuffle(x)#改变x排序
print(x)

[1 2 4 5 3 0 7 6 8 9]


In [20]:
# Or
np.random.permutation(10)

array([1, 3, 7, 6, 2, 5, 9, 0, 8, 4])

## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [21]:
np.random.seed(10)