# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.1'

## Matrix and vector products

Q1. Predict the results of the following code.

In [5]:
x = [1,2]
y = [[4, 1], [2, 2]]
print (np.dot(x, y)) 
print (np.dot(y, x)) #数组的点积
print (np.matmul(x, y))#两个数组的矩阵积
print (np.inner(x, y))
print (np.inner(y, x))#两个数组的内积

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [6]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print (np.dot(y, x))
print (np.matmul(y, x))


[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [8]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print (np.vdot(x, y)) 
print (np.vdot(y, x)) #两个向量的点积
print (np.dot(x.flatten(), y.flatten())) #按行降维后求乘积
print (np.inner(x.flatten(), y.flatten()))
print ((x*y).sum()) 

30
30
30
30
30


Q4. Predict the results of the following code.

In [9]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print (np.inner(x, y))
print (np.inner(y, x))
print (np.outer(x, y))
print (np.outer(y, x)) #求外积

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [30]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)  
#Cholesky 分解是把一个对称正定的矩阵表示成一个下三角矩阵L和其转置的乘积的分解。它要求矩阵的所有特征值必须大于零，故分解的下三角的对角元也是大于零的。
L = np.linalg.cholesky(x)
print(L)
np.array_equal(np.dot(L, L.T.conjugate()), x)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


True

Q6. Compute the qr factorization of x and verify it.

In [29]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
# 一个矩阵的QR分解（QR decomposition）(QR factorization)是将矩阵分解成A=QR,其中Q是一个正交矩阵（QTQ=I)R是上三角矩阵。
q,r = np.linalg.qr(x)
print ('q=\n',q)
print ('r=\n',r)
np.allclose(np.dot(q, r), x)

q=
 [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]]
r=
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


True

Q7. Factor x by Singular Value Decomposition and verify it.

In [28]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
# 奇异值分解 正交阵*对角阵*正交阵
U,s,V = np.linalg.svd(x,full_matrices=False,)
print ('U=\n',U)
print ('s=\n',s)
print ('V=\n',V)
np.allclose(np.dot(U, np.dot(np.diag(s), V)), x)

U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
s=
 [3.       2.236068 2.       0.      ]
V=
 [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


True

## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [37]:
x = np.diag((1, 2, 3))
#特征值和特征向量
np.linalg.eig(x)
eigenvals = np.linalg.eig(x)[0]
print('eigenvals = \n',eigenvals)
eigenvecs = np.linalg.eig(x)[1]
print('eigenvecs = \n',eigenvecs)

eigenvals = 
 [1. 2. 3.]
eigenvecs = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [39]:
print (np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [47]:
x = np.arange(1, 10).reshape((3, 3))
#Frobenius 范数：矩阵x各项元素的绝对值平方的总和
x_norm = np.linalg.norm(x)
print('x_norm=',x_norm)
x_cond = np.linalg.cond(x)
print('x_cond=',x_cond)

x_norm= 16.881943016134134
x_cond= 5.0522794445385096e+16


Q11. Calculate the determinant of x.

In [50]:
x = np.arange(1, 5).reshape((2, 2))
#行列式
np.linalg.det(x)

-2.0000000000000004

Q12. Calculate the rank of x.

In [51]:
x = np.eye(4)
#秩
np.linalg.matrix_rank(x)

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [53]:
x = np.arange(1, 5).reshape((2, 2))
#行列式的符号和自然对数
sign, logdet = np.linalg.slogdet(x)
print('sign:',sign,'logdet:',logdet)


sign: -1.0 logdet: 0.6931471805599455


Q14. Return the sum along the diagonal of x.

In [55]:
x = np.eye(4)
#对角线之和
np.trace(x)

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [58]:
x = np.array([[1., 2.], [3., 4.]])
#逆
x_inv = np.linalg.inv(x)
print(x_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]
