# Random Sampling

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [3]:
np.random.uniform(0,1,6).reshape((3,2))

array([[0.31780337, 0.35389402],
       [0.88611825, 0.067831  ],
       [0.1756105 , 0.1312568 ]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [9]:
x=np.random.standard_normal(1000*1000).reshape((1000,1000))
np.mean(np.random.standard_normal(1000*1000))
np.std(np.random.standard_normal(1000*1000))

0.999767622253051

Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [13]:
#np.random.random_integers(0,3,(3,2))
np.random.randint(0,3+1,(3,2))

array([[1, 0],
       [3, 0],
       [1, 0]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [16]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']
np.random.choice(x,1,p=(0.3,0.5,0.2))

array([b'3 out of 10'], dtype='|S11')

Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [18]:
x=np.arange(10)
np.random.choice(x,3)

array([1, 6, 3])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [27]:
x=np.arange(10)
np.random.shuffle(x)
x

In [26]:
x=np.arange(10)
np.random.permutation(x)

array([0, 1, 8, 2, 5, 3, 6, 9, 7, 4])

## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [29]:
np.random.seed(10)
np.random.get_state()

('MT19937', array([        10,  944463347, 2695371745, 3765730194, 1896634681,
        1176906525,  400883218, 2211307297,  177718231, 1955549916,
         804189755, 1789507666, 4141818827,  715597301, 2901743287,
        1623970424,  291228365,    5879794, 1182012556, 4138111156,
        2620000071, 1767623502, 2486009153, 2127578758, 1603998299,
         762734491, 2254820161, 2400203914, 3979968964, 3734287008,
         179877229,   99739936, 2920487360, 1923087275, 1886536756,
        3171436044, 3559072170, 3061758162, 2660645430, 2111228587,
        3671650106,  103473830, 2629845416, 1050927677, 1449518909,
        1100437209, 1578556262, 3460280018, 1734660517, 2859694565,
        3575428949, 3184220961, 4143296515, 3122556981, 4254119145,
         625908361, 3463792965, 3244711639,  502193630, 1561024209,
        3869151308,  502412904, 3431276358, 3844359032, 2345169607,
        2867049722, 3665239578, 1321812256, 2099796809, 3636300717,
         743061996, 1471948387, 29939