# Array manipulation routines

In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.5'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [8]:
x=np.ones((10,10,3),dtype=np.int)
x.reshape((2,150))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [9]:
x=np.array([1,4,2,5,3,6])
x.tolist()

[1, 4, 2, 5, 3, 6]

Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [12]:
x=np.arange(1,7,1)
x[4]

5

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [15]:
x=np.arange(60).reshape((3,4,5))
x.reshape((4,3,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [17]:
np.arange(12).reshape(3,4).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [28]:
a=np.random.random((3,4))
a.reshape((3,1,4))

array([[0.04004499, 0.6618711 , 0.51994303, 0.81820517],
       [0.35104808, 0.56974223, 0.44590952, 0.5026936 ],
       [0.29183109, 0.52289246, 0.15706863, 0.00107257]])

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [33]:
a=np.random.random((3,4,1))
a.resize((3,4))
a

array([[0.34533634, 0.54021341, 0.7137056 , 0.84584584],
       [0.10293989, 0.84209397, 0.05775932, 0.8302626 ],
       [0.57507196, 0.36856285, 0.01795653, 0.91214626]])

(3L, 4L)


Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [44]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array(((7,8,9),(10,11,12)))
x_y=np.hstack([x,y])
x_y

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [45]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array(((7,8,9),(10,11,12)))
x_y=np.vstack([x,y])
x_y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [59]:
x=np.array([1,2,3])
y=np.array((4,5,6))
x_y=np.vstack([x,y])
x_y.T.reshape(-1)

array([1, 4, 2, 5, 3, 6])

Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [71]:
x=np.array([1,2,3])
y=np.array((4,5,6))
x_y=np.stack([x,y],axis=-1)
#np.stack([x,y],axis=1)
x_y

array([[1, 4],
       [2, 5],
       [3, 6]])

Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [75]:
x=np.arange(1,10,1)
np.split(x,[4,6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [85]:
x=np.array([[0,1,2,4,5,6,3,7],[8,9,10,12,13,14,11,15]],dtype=float)
np.split(x,np.array([6]),axis=1)


[array([[ 0.,  1.,  2.,  4.,  5.,  6.],
        [ 8.,  9., 10., 12., 13., 14.]]), array([[ 3.,  7.],
        [11., 15.]])]

Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [101]:
x=np.vstack([np.arange(8),np.arange(8,16,1)])
np.split(x,2,axis=1)
#np.stack([np.arange(8),np.arange(8,16,1)],axis=0)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]]), array([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])]

Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [103]:
x=np.vstack([np.arange(8),np.arange(8,16,1)])
np.split(x,2,axis=0)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [113]:
x=np.array([0,1,2])
y=np.hstack([x,x])
np.vstack([y,y])

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [117]:
x=np.array([0,1,2])
y=np.stack([x,x],axis=0)
y.reshape(-1,order='F')

array([0, 0, 1, 1, 2, 2])

Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [123]:
X=np.array([0,0,0,1,2,3,0,2,1,0])
np.arange(3,9,1)
X[np.arange(3,9,1)]

array([1, 2, 3, 0, 2, 1])

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [137]:
x=np.array([2,2,1,5,4,5,1,2,3])
import pandas as pd
y=pd.Series(x)
y.value_counts

<bound method IndexOpsMixin.value_counts of 0    2
1    2
2    1
3    5
4    4
5    5
6    1
7    2
8    3
dtype: int32>

Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [140]:
x=np.array([[1,2],[3,4]])
np.flip(x,1)

array([[3, 4],
       [1, 2]])

Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [142]:
x=np.array([[1,2],[3,4]])
np.flip(x,0)

array([[3, 4],
       [1, 2]])

Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [143]:
x=np.array([[1,2],[3,4]])
np.flip(x)

array([[4, 3],
       [2, 1]])

Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [146]:
x=np.array([[1,2,3,4],[5,6,7,8]])
x[:,[3,0,1,2]]

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])